server:
  port: 9099
spring:
  application:
    name: dbConfigCenter
  cloud:
    config:
      server:
        git:
          uri: http://192.168.200.19/mayunbao/dbConfig.git
          username: mayunbao
          password: Qwer123456
          #searchPaths: cloud-config-repo
    consul:
      host: 192.168.200.23
      port: 8500
      discovery:
          healthCheckInterval: 15s
          instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
